$background = rgb(1D1D1F)
$foreground = rgb(FEF0C7)
$color0 = rgb(434346)
$color1 = rgb(1A191F)
$color2 = rgb(44332C)
$color3 = rgb(4A3A35)
$color4 = rgb(6E4E39)
$color5 = rgb(74523B)
$color6 = rgb(BD9F47)
$color7 = rgb(F5E1A6)
$color8 = rgb(AC9E75)
$color9 = rgb(232129)
$color10 = rgb(5A443B)
$color11 = rgb(634D46)
$color12 = rgb(92684C)
$color13 = rgb(9A6D4F)
$color14 = rgb(FCD45F)
$color15 = rgb(F5E1A6)
