$background = rgb(2B2B2E)
$foreground = rgb(E2E1E3)
$color0 = rgb(505053)
$color1 = rgb(1E202B)
$color2 = rgb(21212B)
$color3 = rgb(43242D)
$color4 = rgb(54262E)
$color5 = rgb(9B3238)
$color6 = rgb(827E83)
$color7 = rgb(CECBCF)
$color8 = rgb(908E91)
$color9 = rgb(282B39)
$color10 = rgb(2C2B39)
$color11 = rgb(59303C)
$color12 = rgb(70323E)
$color13 = rgb(CF424B)
$color14 = rgb(ADA8AF)
$color15 = rgb(CECBCF)
