# Monitor Configuration
# https://wiki.hyprland.org/Configuring/Monitors/
# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.


# Monitors
monitor=DP-1,1920x1080@240,0x0,1

# AMD stuff
render {
    direct_scanout = true
}

misc {
    vrr = 0
}
