windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim on, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur on, match:class ^(xwaylandvideobridge)$
windowrule = no_focus on, match:class ^(xwaylandvideobridge)$

windowrule = match:class ^([Kk]itty)$, workspace 1
windowrule = match:class ^([Mm]ozilla zen(-alpha|-beta))$, workspace 3
windowrule = match:class ^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable)?)$, workspace 3
windowrule = match:class ^([Mm]inecraft [Ll]auncher)$, workspace 4
windowrule = match:class ^([Ss]team)$, workspace 5
windowrule = match:class ^([Ll]utris)$, workspace 5
windowrule = match:class ^([Dd]iscord)$, workspace 2
windowrule = match:class ^([Ww]ebCord)$, workspace 2
windowrule = match:class ^([Vv]esktop)$, workspace 2
windowrule = match:class ^([Ff]erdium)$, workspace 2
windowrule = match:class ^([Ss]ignal [Dd]esktop)$, workspace 2

windowrule = match:class ^(virt-manager)$, workspace 6 silent
windowrule = match:class ^([Aa]udacious)$, workspace 9 silent
