theme = "onedark"

[editor]
line-number = "relative"
true-color = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
character = "╎"
render = true
